config/routes.rb
ADPLib::Application.routes.draw do
  resources :checkouts

  devise_for :users

  resources :dedications

  resources :books

  get "home/index"

	root :to => "home#index"
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :users, :through => :checkouts
	acts_as_indexed :fields => [:description, :title, :author]	
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

app/models/dedication.rb
class Dedication < ActiveRecord::Base
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
	
	has_many :books, :through => :checkouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.xml
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to(@book, :notice => 'Book was successfully created.') }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  # GET /checkouts
  # GET /checkouts.xml
  def index
    @checkouts = Checkout.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @checkouts }
    end
  end

  # GET /checkouts/1
  # GET /checkouts/1.xml
  def show
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @checkout }
    end
  end

  # GET /checkouts/new
  # GET /checkouts/new.xml
  def new
    @checkout = Checkout.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @checkout }
    end
  end

  # GET /checkouts/1/edit
  def edit
    @checkout = Checkout.find(params[:id])
  end

  # POST /checkouts
  # POST /checkouts.xml
  def create
    @checkout = Checkout.new(params[:checkout])

    respond_to do |format|
      if @checkout.save
        format.html { redirect_to(@checkout, :notice => 'Checkout was successfully created.') }
        format.xml  { render :xml => @checkout, :status => :created, :location => @checkout }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @checkout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /checkouts/1
  # PUT /checkouts/1.xml
  def update
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      if @checkout.update_attributes(params[:checkout])
        format.html { redirect_to(@checkout, :notice => 'Checkout was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @checkout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.xml
  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy

    respond_to do |format|
      format.html { redirect_to(checkouts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/dedications_controller.rb
class DedicationsController < ApplicationController
  # GET /dedications
  # GET /dedications.xml
  def index
    @dedications = Dedication.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dedications }
    end
  end

  # GET /dedications/1
  # GET /dedications/1.xml
  def show
    @dedication = Dedication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dedication }
    end
  end

  # GET /dedications/new
  # GET /dedications/new.xml
  def new
    @dedication = Dedication.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dedication }
    end
  end

  # GET /dedications/1/edit
  def edit
    @dedication = Dedication.find(params[:id])
  end

  # POST /dedications
  # POST /dedications.xml
  def create
    @dedication = Dedication.new(params[:dedication])

    respond_to do |format|
      if @dedication.save
        format.html { redirect_to(@dedication, :notice => 'Dedication was successfully created.') }
        format.xml  { render :xml => @dedication, :status => :created, :location => @dedication }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dedication.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dedications/1
  # PUT /dedications/1.xml
  def update
    @dedication = Dedication.find(params[:id])

    respond_to do |format|
      if @dedication.update_attributes(params[:dedication])
        format.html { redirect_to(@dedication, :notice => 'Dedication was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dedication.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dedications/1
  # DELETE /dedications/1.xml
  def destroy
    @dedication = Dedication.find(params[:id])
    @dedication.destroy

    respond_to do |format|
      format.html { redirect_to(dedications_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/dedications_helper.rb
module DedicationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :pub_date %><br />
    <%= f.date_select :pub_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Pub date</th>
    <th>Description</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.pub_date %></td>
    <td><%= book.description %></td>
    <td><%= book.location %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Pub date:</b>
  <%= @book.pub_date %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Location:</b>
  <%= @book.location %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/checkouts/_form.html.erb
<%= form_for(@checkout) do |f| %>
  <% if @checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>

      <ul>
      <% @checkout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Editing checkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<h1>Listing checkouts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkouts.each do |checkout| %>
  <tr>
    <td><%= link_to 'Show', checkout %></td>
    <td><%= link_to 'Edit', edit_checkout_path(checkout) %></td>
    <td><%= link_to 'Destroy', checkout, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checkout', new_checkout_path %>

app/views/checkouts/new.html.erb
<h1>New checkout</h1>

<%= render 'form' %>

<%= link_to 'Back', checkouts_path %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>

app/views/dedications/_form.html.erb
<%= form_for(@dedication) do |f| %>
  <% if @dedication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dedication.errors.count, "error") %> prohibited this dedication from being saved:</h2>

      <ul>
      <% @dedication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dedications/edit.html.erb
<h1>Editing dedication</h1>

<%= render 'form' %>

<%= link_to 'Show', @dedication %> |
<%= link_to 'Back', dedications_path %>

app/views/dedications/index.html.erb
<h1>Listing dedications</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dedications.each do |dedication| %>
  <tr>
    <td><%= link_to 'Show', dedication %></td>
    <td><%= link_to 'Edit', edit_dedication_path(dedication) %></td>
    <td><%= link_to 'Destroy', dedication, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dedication', new_dedication_path %>

app/views/dedications/new.html.erb
<h1>New dedication</h1>

<%= render 'form' %>

<%= link_to 'Back', dedications_path %>

app/views/dedications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_dedication_path(@dedication) %> |
<%= link_to 'Back', dedications_path %>

app/views/home/index.html.erb
<h1>Welcome to the Alpha Delta Phi Middletown Chapter online library.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ADPLib</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav">
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>.
		<%= link_to "Sign Out", destroy_user_session_path %>
	<% else %>
		<%= link_to "Sign In", new_user_session_path %>
		<%= link_to "Sign Up", new_user_registration_path %>
	<% end %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>